version: '3.6'

services:

  aws:
    build: .
    entrypoint: aws
    volumes:
      - './storage:/storage'

  command:
    build: .
    volumes:
      - './commands:/data'

  saw:
    build: .
    entrypoint: saw